# Config file for cargo about
# For all options see https://embarkstudios.github.io/cargo-about/cli/generate/config.html

# If you add a license in the following section also consider changing deny.toml
accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "EPL-2.0",
    "ISC",
    "MIT",
    # Unicode-3.0 is not (yet) on the Eclipse Foundation's list of approved licenses
    # however, all of its predecessors are, thus we assume that 3.0 is also ok to use
    "Unicode-3.0",
    "Zlib",
]

targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl"
]

ignore-dev-dependencies = true

[unicode-ident]
accepted = ["Unicode-DFS-2016"]
